msgid ""
msgstr ""
"Project-Id-Version: pylav\n"
"POT-Creation-Date: 2023-01-31 20:21+0000\n"
"PO-Revision-Date: 2023-01-31 22:05\n"
"Last-Translator: \n"
"Language-Team: Hungarian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.4.2\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: pylav\n"
"X-Crowdin-Project-ID: 535244\n"
"X-Crowdin-Language: hu\n"
"X-Crowdin-File: /lib/pylav/extension/bundled_node/locales/messages.po\n"
"X-Crowdin-File-ID: 2377\n"
"Language: hu_HU\n"

#: pylav/extension/bundled_node/manager.py:227
msgid "You are attempting to run the managed Lavalink node on an unsupported machine architecture"
msgstr "A felügyelt Lavalink csomópontot nem támogatott géparchitektúrán próbálja futtatni"

#: pylav/extension/bundled_node/manager.py:452
msgid "The output of `{java_exc} -version` was unexpected\n"
"{version_info}"
msgstr "A \"{java_exc} -verzió' váratlan volt\n"
"{version_info}"

#: pylav/extension/bundled_node/manager.py:472
msgid "Port {port} already in use. Managed Lavalink startup aborted"
msgstr "Kikötő {port} már használatban van. A kezelt Lavalink indítása megszakadt"

#: pylav/extension/bundled_node/manager.py:477
msgid "Lavalink failed to start: {line}"
msgstr "A Lavalink nem indult el: {line}"

