msgid ""
msgstr ""
"Project-Id-Version: pylav\n"
"POT-Creation-Date: 2023-01-31 20:21+0000\n"
"PO-Revision-Date: 2023-01-31 20:32\n"
"Last-Translator: \n"
"Language-Team: Japanese\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: redgettext 3.4.2\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Crowdin-Project: pylav\n"
"X-Crowdin-Project-ID: 535244\n"
"X-Crowdin-Language: ja\n"
"X-Crowdin-File: /lib/pylav/extension/bundled_node/locales/messages.po\n"
"X-Crowdin-File-ID: 2377\n"
"Language: ja_JP\n"

#: pylav/extension/bundled_node/manager.py:227
msgid "You are attempting to run the managed Lavalink node on an unsupported machine architecture"
msgstr "サポートされていないマシンアーキテクチャで管理されているLavalinkノードを実行しようとしています"

#: pylav/extension/bundled_node/manager.py:452
msgid "The output of `{java_exc} -version` was unexpected\n"
"{version_info}"
msgstr "`{java_exc} -version` の出力が予期しないものでした\n"
"{version_info}"

#: pylav/extension/bundled_node/manager.py:472
msgid "Port {port} already in use. Managed Lavalink startup aborted"
msgstr "ポート {port} は既に使用されています。管理された Lavalink 起動は中止されました。"

#: pylav/extension/bundled_node/manager.py:477
msgid "Lavalink failed to start: {line}"
msgstr "ラバリンクの開始に失敗しました: {line}"

